version: '3.9'

services:
  data:
    build: ./db-config
    container_name: ms_sql
    image: ms_sql
    ports:
      - "1433:1433"
    networks:
      - lab-net-1
  personapi-dotnet:
    build: ./personapi-dotnet
    container_name: personapi-dotnet
    image: personapidotnet
    ports:
      - "32770:80"
    depends_on:
      - data
    networks:
      - lab-net-1
networks:
  lab-net-1:
    name: lab-net-1
    driver: bridge